from http.cookies import SimpleCookie
import random
import string

_TTWID_REGISTER_URL = "https://ttwid.bytedance.com/ttwid/union/register/"
_TTWID_REGISTER_DATA = (
    '{"region":"cn","aid":1768,"needFid":false,"service":"www.ixigua.com",'
    '"migrate_info":{"ticket":"","source":"node"},"cbUrlProtocol":"https",'
    '"union":true}'
).encode()


def _cookie_from_set_cookie_header(set_cookie_header, name):
    if not set_cookie_header:
        return None
    cookie_jar = SimpleCookie()
    try:
        cookie_jar.load(set_cookie_header)
    except Exception:
        return None
    morsel = cookie_jar.get(name)
    return morsel.value if morsel else None


_DOUYIN_HOME = "https://www.douyin.com/"


def ensure_douyin_web_cookies(ie, video_id, user_agent):
    cookies = ie._get_cookies(_DOUYIN_HOME)

    if not cookies.get("ttwid"):
        res = ie._download_webpage_handle(
            _TTWID_REGISTER_URL,
            video_id,
            note="Downloading ttwid cookie",
            errnote="Unable to download ttwid cookie",
            fatal=False,
            data=_TTWID_REGISTER_DATA,
            headers={
                "User-Agent": user_agent,
                "Content-Type": "application/json",
                "Referer": _DOUYIN_HOME,
            },
        )
        if res and res is not False:
            _, urlh = res
            ttwid = _cookie_from_set_cookie_header(
                urlh.headers.get("Set-Cookie"), "ttwid"
            )
            if ttwid:
                ie._set_cookie(".douyin.com", "ttwid", ttwid)

    if not ie._get_cookies(_DOUYIN_HOME).get("s_v_web_id"):
        ie._download_webpage_handle(
            _DOUYIN_HOME,
            video_id,
            note="Downloading Douyin homepage for cookies",
            errnote="Unable to download Douyin homepage for cookies",
            fatal=False,
            headers={
                "User-Agent": user_agent,
                "Referer": _DOUYIN_HOME,
            },
            impersonate=True,
        )
        # s_v_web_id is generated by browser JS from __ac_nonce.
        # If the homepage visit didn't set it (no JS execution), generate a
        # valid-format value ourselves — Douyin validates format, not content.
        if not ie._get_cookies(_DOUYIN_HOME).get("s_v_web_id"):
            chars = string.ascii_letters + string.digits
            fake_id = "verify_" + "".join(random.choices(chars, k=8))
            ie._set_cookie(".douyin.com", "s_v_web_id", fake_id)
            ie.to_screen(f"Generated s_v_web_id: {fake_id}")
